[package]
name = "cpal"
version = "0.1.0"
authors = ["Sam Saint-Pettersen <s.stpettersen+github@gmail.com>"]

[dependencies]
clioptions = "0.1.0"
ssid = { git = "https://github.com/stpettersens/ssid.git" }
serde = "1.0.5"
serde_derive = "1.0.5"
serde_json = "1.0.2"
